name: CI

on:
  merge_group:
  pull_request:
  push: # WARNING: Renovate sometimes automerges without PR, so we MUST build and test renovate/** branches
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.compare || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Debug info
        run: |
          cat <<EOF
          Scratch environment: ${{ vars.SCRATCH_ENV || '<none>' }}
          Node version: $(node --version)
          NPM version: $(npm --version)
          GitHub ref: ${{ github.ref }}
          GitHub head ref: ${{ github.head_ref }}
          Working directory: $(pwd)
          EOF

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          filters: ./.github/path-filters.yml

      - if: ${{ steps.filter.outputs.any-workspace == 'true' }}
        uses: ./.github/actions/install-dependencies

      - name: Build packages
        if: ${{ steps.filter.outputs.any-workspace == 'true' }}
        run: npm run build

      - name: Store build artifacts
        if: ${{ steps.filter.outputs.any-workspace == 'true' }}
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: build
          path: |
            packages/**/build
            packages/**/dist
            packages/**/playground

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.build.outputs.packages) }}
        exclude:
          - package: global
          - package: any-workspace
    name: Test ${{ matrix.package }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - uses: ./.github/actions/install-dependencies
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: build
          path: packages
      - uses: ./.github/actions/test-package
        with:
          package_name: ${{ matrix.package }}
