name: Update i18n

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: 0 0 * * * # daily at midnight UTC = 7-8pm US Eastern

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Info
        # https://docs.github.com/en/actions/reference/security/secure-use#use-an-intermediate-environment-variable
        env:
          GH_HEAD_REF: ${{ github.head_ref }}
        run: |
          cat <<EOF
          Node version: $(node --version)
          NPM version: $(npm --version)
          GitHub ref: ${{ github.ref }}
          GitHub head ref: ${GH_HEAD_REF}
          EOF
      - name: Setup
        uses: ./.github/actions/install-dependencies
      - name: Update i18n in scratch-vm
        uses: ./.github/actions/update-i18n
        with:
          package_name: scratch-vm
          tx_token: ${{ secrets.TX_TOKEN }}
      - name: Update i18n in scratch-gui
        uses: ./.github/actions/update-i18n
        with:
          package_name: scratch-gui
          tx_token: ${{ secrets.TX_TOKEN }}
